
# On Windows copy into C:\decent_ci_runner and update
# On Linux copy into /usr/local/etc and update

run_dir: "/home/jason/decent_ci_run_dir"
branch_name: "add_windows_packer"

virtual_machine_manager_only: true

virtual_machine_virtualbox_executable: "C:/Program Files/Oracle/VirtualBox/VBoxManage.exe"
virtual_machine_vmware_executable: "C:/Program Files (x86)/VMWare/VMware Workstation/vmrun.exe"

virtual_machine_list:
  - name: /path/to/vmx
    type: vmware
    revert_snapshot: snapshot name
  - name: VirtualBoxName / uuid
    type: virtualbox
    revert_snapshot: SnapshotName / uuid

