
# On Windows copy into C:\decent_ci_runner and update
# On Linux copy into /usr/local/etc and update

#run_dir: "C:/CI"
#run_dir: /Users/jason/decent_ci_run_dir
run_dir: "/home/jason/decent_ci_run_dir"
branch_name: "security_enhancements"
environment: 
#  DECENT_CI_SKIP_DAILY_TASKS: false
#  DECENT_CI_SKIP_TEST: false
  DECENT_CI_BRANCH_FILTER: ".*"
  DECENT_CI_COMPILER_FILTER: ".*"
test_mode: true
github_token: "ABCDEF1234567890"
options:
  - "--no-verbose"
# list of regex for users allowed to have
# external PR's built
  - "--external_users=\".*\""
# branch to pull trusted files (ie files containing known users info)
  - "--trusted_branch=develop"
# You probably want to uncomment this on Windows
#  - "--disable-ssl-verification"
repositories:
  - "NREL/EnergyPlus"  

shutdown_after_run: false

virtual_machine_manager_only: false

